language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# Install dependencies.
install:
  - pip install -r requirements.txt

# Run linting and tests.
script:
  - pylint .

# Turn email notifications off.
notifications:
  email: false
